Enhancement/button states
FooCamp/foocamp-ap pull request #4
Opened 2021-08-07 19:59 UTC by cricar6

2021-08-07 20:29 UTC, javiermlovo approved these changes

2021-08-20 00:45 UTC, Cruzlex7 commented on components/layouts/BigImageLayout.js
> +        { title
it could be 
```suggestion
        {title && (<h2> {title} </h2>)}
```

2021-08-20 00:46 UTC, Cruzlex7 commented on pages/index.js
> +  const pageData = await getPageData('inicio');
must be a constat

2021-08-20 00:50 UTC, Cruzlex7 commented on pages/index.js
> +          title={joinUsSection.fields.title}
provide only one object as a prop that contains al this info.

2021-08-20 00:52 UTC, Cruzlex7 requested changes
This PR must be merge with dev, not with main branch.

2021-08-20 00:54 UTC, closed without merging