Feature/pages hero section
FooCamp/foocamp-ap pull request #5
Opened 2021-08-18 07:52 UTC by juanbravozu

### Changes

* Added Hero component file, with it's respective style file.
* Added an arrow icon.
* Added mixin to center absolute positioned objects horizontally.
* Added validation in index file to render the Hero based on the data received from Contentful.

### Observations

* Social media icons are black instead of white
* A weird character is displayed on the Hero title

![image](https://user-images.githubusercontent.com/43077180/129859642-3d36010d-5c97-411a-b14d-cf0205d42d2b.png)

2021-08-18 18:41 UTC, javiermlovo approved these changes
I agree

2021-08-18 21:36 UTC, cricar6 approved these changes

2021-08-18 22:16 UTC, tatarodriguez11 commented on package-lock.json
> +    "@contentful/rich-text-react-renderer": {
éste archivo no deberia estar en el commit

2021-08-18 22:17 UTC, tatarodriguez11 commented on pages/index.js
> +        if (component.sys.contentType.sys.id === 'hero') {
yo haria algo como 
`!!(component.sys.contentType.sys.id === 'hero') && (<Hero ..... />`

2021-08-18 22:19 UTC, tatarodriguez11 commented on styles/abstract/_mixins.scss
> +@mixin absolute-center-horizontal {
es algo que se va a estar usando constantemente?

2021-08-18 22:22 UTC, tatarodriguez11 commented on styles/ayp.scss
> +@import './common/hero.scss';
no deberia ir en common, deberia haber una carpeta de componentes, o algo que les brinde una mejor organizacion de los archivos

2021-08-18 22:27 UTC, tatarodriguez11 commented on styles/common/hero.scss
> +
está faltando la propiedad de display para mobile, en caso de un resize

2021-08-18 22:29 UTC, juanbravozu commented on styles/ayp.scss
> +@import './common/hero.scss';
Crees que en la carpeta de layout sería adecuado?

2021-08-18 22:36 UTC, juanbravozu commented on styles/abstract/_mixins.scss
> +@mixin absolute-center-horizontal {
Viendo el diseño, no creo que se utilice demasiado fuera de los usos que le di en este feature. Sería mejor quitarlo y simplemente poner esos estilos manualmente?

2021-08-18 22:37 UTC, juanbravozu commented on styles/common/hero.scss
> +
La flecha solo va en mobile, en pantallas de mayor tamaño tiene display: none

2021-08-18 23:04 UTC, juanbravozu commented on package-lock.json
> +    "@contentful/rich-text-react-renderer": {
@tatarodriguez11 Debería borrar esta parte del archivo y subirlo de nuevo junto al resto de cambios?

2021-08-18 23:22 UTC, Cruzlex7 commented on components/Hero.js
> +          {socialMedia.map((item) => (
we can use beacause we are not using item itself directly only his fields props
```suggestion
          {socialMedia.map(      ({ fields: { title, icon, link } })     ) => ( 
```
and at the bottom, you can access (title, icon, and link) directly.

2021-08-18 23:24 UTC, Cruzlex7 commented on package-lock.json
> +    "@contentful/rich-text-react-renderer": {
Este archivo se utiliza para bloquear versiones de recursos o paquetes de terceros que usemos en nuestro proyecto, normalmente se actualiza cada vez que se hace un npm install y cambia una version de aguno de esos paquetes, si no se hace un updagrate del sistema general o un improvement de un paquete depreacted, no debería actualizarse.

2021-08-18 23:25 UTC, Cruzlex7 commented on pages/index.js
> +        if (component.sys.contentType.sys.id === 'hero') {
'hero' must be a constant.

2021-08-18 23:29 UTC, Cruzlex7 commented on pages/index.js
> +              key={component.sys.id}
Try to use destructuring a most as possible to avoid changing properties references.

2021-08-18 23:37 UTC, Cruzlex7 commented on styles/abstract/_mixins.scss
> +@mixin absolute-center-horizontal {
si no se reutiliza es mejor dejarlo en un lugar. O de lo contrario dejarlo como minxin y difundirlo a los demás devs para que se use como regla general. cada vez que se quiera centrar se use este mixing.

2021-08-18 23:42 UTC, Cruzlex7 commented on styles/abstract/_mixins.scss
> +  left: 50%;
Why not use display-flex ? flex-flow: row nowrap; justify-content: center; aling-content: center ?

2021-08-18 23:43 UTC, Cruzlex7 commented on styles/ayp.scss
> +@import './common/hero.scss';
Responder con una pregunta hace el flujo de desarrollo muy lento, según el comentario toma una acción y vuelve y se valida.

2021-08-18 23:45 UTC, Cruzlex7 commented on styles/common/hero.scss
> +  min-height: 575px;
use constans for static and absolute values.

2021-08-19 23:16 UTC, Cruzlex7 commented on constants/sectionsId.js
> +export const HERO_SECTION = 'hero';
there is not a general constants file ?

2021-08-19 23:25 UTC, Cruzlex7 commented on pages/index.js
> +        || (<p key={id}>Test</p>))}
test?

2021-08-19 23:58 UTC, Cruzlex7 approved these changes

2021-08-20 00:34 UTC, Cruzlex7 requested changes
En cada componente estas iterando por toda la respuesta del servidor y comprobando por Id si es el compoenente que se debe pintar, eso no debe ser así. Debe existir un componente padre (Hight order component) quien sea quien organice la información y la pase de forma plana al componente correspondiente.

2021-08-23 20:06 UTC, tatarodriguez11 commented on components/Home.js
> +        (!!(contentType.sys.id === HERO_SECTION) && <Hero key={id} fields={fields} />)
creo que podriamos tener un mejor approach para ésto, porque si bien necesitan saber que es lo que deben mostrar, debemos hacerlo de la forma mas reusable posible, sugeriría crear una funcion en utils que tenga los cases posibles y resuelva el nombre del componente a mostrar.
Para evitar que en éste HOC tengan que estar importando mas y mas componentes.

2021-08-23 20:08 UTC, tatarodriguez11 commented on styles/layout/hero.scss
> +  --min-height: 575px;
chicos si van a usar variables de sass, que todo sea en variables de sass, o si van a usar variables de css que todo sea variables de css, para mantener una consistencia.

2021-08-23 20:17 UTC, javiermlovo approved these changes

2021-08-23 22:59 UTC, Cruzlex7 commented on components/Hero.js
> +      <img src={img} alt="" className="hero-background" />
alt empty?  must no be there or have a value!

2021-08-23 23:02 UTC, Cruzlex7 commented on components/Layout.js
>      <div className="layout">
The Layout component is only working as a wrapper with this change.

2021-08-23 23:05 UTC, Cruzlex7 commented on components/Layout.js
>      <div className="layout">
Where is this component used?

2021-08-23 23:08 UTC, Cruzlex7 commented on components/Hero.js
> +      <img src="/icons/arrow-down.svg" className="hero-arrow" alt="" />
shouldn't be used the svg tag? like [Here](https://stackoverflow.com/questions/34097191/using-a-svg-file-in-html-from-a-url)

2021-08-23 23:14 UTC, juanbravozu commented on components/Hero.js
> +      <img src={img} alt="" className="hero-background" />
I used and empty alt to avoid problems for screen readers, as said by these articles:

- https://accessibleweb.com/question-answer/when-should-i-use-a-null-or-empty-alt-tag/
- https://davidwalsh.name/accessibility-tip-empty-alt-attributes#:~:text=Images%20with%20only%20visual%20value,only%20is%20just%20as%20useless.
- https://www.w3.org/WAI/tutorials/images/decorative/

2021-08-27 23:41 UTC, javiermlovo approved these changes

2021-08-27 23:42 UTC, juanbravozu commented on styles/components/hero.scss
> +    margin-top: 64px;
Fixed

2021-08-27 23:43 UTC, tatarodriguez11 approved these changes

2021-08-27 23:43 UTC, merged